language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ganeshyedla/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ganeshyedla/docker-react npm run test

